### ISSUE TITLE
`CLI#base` commands do not properly catch non-existent arguments / flags

### ISSUE THREAD

**Issue by seanrcollings** [seanrcollings/arc#89]
With:
```
@cli.base()
@cli.command()
def run():
    """Open the venture selection menu"""
    projects = get_projects()
    choice = pick(projects, config, OpenContext.DEFAULT)
    execute(choice)

```
Given a non-valid argument, arc does not properly exit
```
$ venture --test
Traceback (most recent call last):
  File "/home/sean/.local/bin/venture", line 8, in <module>
    sys.exit(cli())
  File "/home/sean/.local/lib/python3.9/site-packages/arc/cli.py", line 49, in __call__
    return run(self, execute)
  File "/home/sean/.local/lib/python3.9/site-packages/arc/cli.py", line 188, in run
    return command.run(command_node)
  File "/home/sean/.local/lib/python3.9/site-packages/arc/command/command.py", line 148, in run
    value = self.execute(command_node)
  File "/home/sean/.local/lib/python3.9/site-packages/arc/command/keyword_command.py", line 18, in execute
    return self.function(**args)
  File "/home/sean/.local/lib/python3.9/site-packages/arc/utils.py", line 46, in decorator
    return_value = func(*args, **kwargs)
  File "/home/sean/.local/lib/python3.9/site-packages/arc/command/helpers.py", line 140, in wrapper
    return function(*args, **kwargs, **command.hidden_args)
  File "/home/sean/.local/lib/python3.9/site-packages/arc/cli.py", line 78, in __default
    self.default_action(**kwargs)
  File "/home/sean/.local/lib/python3.9/site-packages/arc/command/command.py", line 52, in __call__
    return self.function(*args, **kwargs)
  File "/home/sean/.local/lib/python3.9/site-packages/arc/utils.py", line 46, in decorator
    return_value = func(*args, **kwargs)
  File "/home/sean/.local/lib/python3.9/site-packages/arc/command/helpers.py", line 140, in wrapper
    return function(*args, **kwargs, **command.hidden_args)
TypeError: run() got an unexpected keyword argument 'test'
```

**Comment by seanrcollings** [comment]
Resolved!
